import { APP_INITIALIZER, ApplicationConfig, ErrorHandler, importProvidersFrom, provideZoneChangeDetection } from '@angular/core'
import { GlobalErrorHandler } from './core/services/global-error.handler'
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Archive,
  BookOpen,
  Camera,
  LayoutDashboard,
  CalendarClock,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleUserRound,
  CircleX,
  ClipboardList,
  CookingPot,
  CookingPotIcon,
  Copy,
  Download,
  Edit,
  Eye,
  EyeOff,
  Sparkles,
  ScanText,
  FileDown,
  FilePlus,
  Filter,
  Flame,
  FlaskConical,
  GripVertical,
  History,
  Image,
  Info,
  Library,
  Lock,
  LogOut,
  LucideAngularModule,
  MapPin,
  Menu,
  Minus,
  Package,
  PanelLeftClose,
  PanelRightClose,
  Pencil,
  Plus,
  PlusCircle,
  Printer,
  RotateCcw,
  Save,
  Scale,
  Search,
  Settings,
  ShieldAlert,
  ShoppingCart,
  Star,
  Table2,
  Tag,
  Tags,
  Timer,
  Trash2,
  Truck,
  TrendingUp,
  Upload,
  Utensils,
  UtensilsCrossed,
  X
} from 'lucide-angular';
import { KitchenStateService } from '@services/kitchen-state.service';
import { provideHttpClient, withInterceptors } from '@angular/common/http'
import { authInterceptor } from './core/interceptors/auth.interceptor'
import { TranslationService } from '@services/translation.service';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    KitchenStateService,
    provideHttpClient(withInterceptors([authInterceptor])),
    {
      provide: APP_INITIALIZER,
      useFactory: (transService: TranslationService) => () => transService.loadGlobalDictionary(),
      deps: [TranslationService],
      multi: true
    },
    importProvidersFrom(
      LucideAngularModule.pick({
        Camera,
        Minus,
        Plus,
        Trash2,
        Edit,
        ArrowLeft,
        Pencil,
        Save,
        ArrowRight,
        ShieldAlert,
        X,
        FlaskConical,
        TrendingUp,
        Scale,
        AlertCircle,
        AlertTriangle,
        Tag,
        Tags,
        ChevronLeft,
        ChevronRight,
        Image,
        Search,
        PlusCircle,
        FilePlus,
        Utensils,
        ChevronDown,
        Timer,
        Menu,
        ArrowUpDown,
        ArrowUp,
        ArrowDown,
        Truck,
        Package,
        CalendarClock,
        RotateCcw,
        History,
        BookOpen,
        Copy,
        Flame,
        CookingPot,
        MapPin,
        PanelRightClose,
        Filter,
        PanelLeftClose, 
        Info,
        Printer,
        UtensilsCrossed,
        ChevronUp,
        Circle,
        CircleCheck,
        CircleX,
        LayoutDashboard,
        Library,
        Table2,
        ShoppingCart,
        LogOut,
        GripVertical,
        Archive,
        Download,
        Upload,
        CircleUserRound,
        ClipboardList,
        Settings,
        Eye,
        EyeOff,
        FileDown,
        CookingPotIcon,
        Star,
        Lock,
        Sparkles,
        ScanText
      })
    )
  ]
};

