const { Schema, model } = require('mongoose');

/**
 * Generic entity document.
 *
 * _id  — 5-char alphanumeric string generated by Angular's makeId().
 *         Accepted as-is so localStorage data can be migrated without re-keying.
 * entityType — Angular localStorage key, e.g. 'PRODUCT_LIST', 'RECIPE_LIST'.
 * data — Full entity object (which also embeds _id for symmetry with localStorage shape).
 */
const entitySchema = new Schema(
  {
    _id: { type: String },
    entityType: { type: String, required: true },
    data: { type: Schema.Types.Mixed, required: true },
  },
  { timestamps: false }
);

entitySchema.index({ entityType: 1 });

module.exports = model('Entity', entitySchema);
