"""
patch_atlas_by_id.py — One-off backfill script.

Updates __master__ products in Atlas (and Local) by their MongoDB _id directly.
Nutrition data was generated by Gemini for all 117 products missing nutrition.

Usage:
  python patch_atlas_by_id.py           # dry run (logs what would change)
  python patch_atlas_by_id.py --write   # actually updates the DB
"""

import argparse
import io
import logging
import sys

import pymongo

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

NUTRITION_BY_ID = [
  {"id": "cFTQ4", "energy_kcal": 0, "protein_g": 0.0, "carbs_g": 0.0, "sugars_g": 0.0, "fat_g": 0.0, "fiber_g": 0.0, "sodium_g": 38.7},
  {"id": "tlPkz", "energy_kcal": 355, "protein_g": 12.5, "carbs_g": 73.0, "sugars_g": 3.0, "fat_g": 1.5, "fiber_g": 3.0, "sodium_g": 0.005},
  {"id": "XaAxs", "energy_kcal": 101, "protein_g": 1.0, "carbs_g": 25.8, "sugars_g": 22.1, "fat_g": 0.1, "fiber_g": 0.3, "sodium_g": 0.91},
  {"id": "uPBQ5", "energy_kcal": 120, "protein_g": 2.8, "carbs_g": 4.2, "sugars_g": 4.2, "fat_g": 9.0, "fiber_g": 0.0, "sodium_g": 0.04},
  {"id": "SmwXd", "energy_kcal": 250, "protein_g": 5.4, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 24.5, "fiber_g": 0.0, "sodium_g": 0.32},
  {"id": "NTdiU", "energy_kcal": 228, "protein_g": 19.6, "carbs_g": 8.9, "sugars_g": 0.5, "fat_g": 13.7, "fiber_g": 33.2, "sodium_g": 0.021},
  {"id": "lioVy", "energy_kcal": 168, "protein_g": 2.6, "carbs_g": 4.0, "sugars_g": 4.0, "fat_g": 15.0, "fiber_g": 0.0, "sodium_g": 0.04},
  {"id": "0u6n6", "energy_kcal": 126, "protein_g": 11.0, "carbs_g": 2.0, "sugars_g": 2.0, "fat_g": 9.0, "fiber_g": 0.0, "sodium_g": 0.36},
  {"id": "jijdY", "energy_kcal": 95, "protein_g": 9.0, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 5.0, "fiber_g": 0.0, "sodium_g": 0.4},
  {"id": "fIX2h", "energy_kcal": 95, "protein_g": 9.0, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 5.0, "fiber_g": 0.0, "sodium_g": 0.4},
  {"id": "UOf3q", "energy_kcal": 60, "protein_g": 3.3, "carbs_g": 4.9, "sugars_g": 4.9, "fat_g": 3.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "m25QH", "energy_kcal": 360, "protein_g": 6.8, "carbs_g": 79.5, "sugars_g": 0.1, "fat_g": 0.6, "fiber_g": 1.3, "sodium_g": 0.001},
  {"id": "enTDT", "energy_kcal": 95, "protein_g": 9.0, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 5.0, "fiber_g": 0.0, "sodium_g": 0.4},
  {"id": "2zbRp", "energy_kcal": 255, "protein_g": 26.0, "carbs_g": 0.1, "sugars_g": 0.1, "fat_g": 15.0, "fiber_g": 0.0, "sodium_g": 0.65},
  {"id": "uMRP9", "energy_kcal": 355, "protein_g": 12.5, "carbs_g": 73.0, "sugars_g": 3.0, "fat_g": 1.5, "fiber_g": 3.0, "sodium_g": 0.005},
  {"id": "0SCVy", "energy_kcal": 350, "protein_g": 23.0, "carbs_g": 0.1, "sugars_g": 0.1, "fat_g": 28.0, "fiber_g": 0.0, "sodium_g": 0.65},
  {"id": "g5uLN", "energy_kcal": 60, "protein_g": 3.3, "carbs_g": 4.9, "sugars_g": 4.9, "fat_g": 3.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "gHC8h", "energy_kcal": 48, "protein_g": 3.2, "carbs_g": 4.5, "sugars_g": 4.5, "fat_g": 2.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "fIiQf", "energy_kcal": 48, "protein_g": 3.2, "carbs_g": 4.5, "sugars_g": 4.5, "fat_g": 2.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "OG5fV", "energy_kcal": 105, "protein_g": 9.5, "carbs_g": 4.0, "sugars_g": 4.0, "fat_g": 5.0, "fiber_g": 0.0, "sodium_g": 0.12},
  {"id": "lbfPQ", "energy_kcal": 105, "protein_g": 9.0, "carbs_g": 4.5, "sugars_g": 4.5, "fat_g": 5.0, "fiber_g": 0.0, "sodium_g": 0.55},
  {"id": "5TAei", "energy_kcal": 94, "protein_g": 5.1, "carbs_g": 14.5, "sugars_g": 4.5, "fat_g": 0.5, "fiber_g": 4.8, "sodium_g": 0.42},
  {"id": "TTCmc", "energy_kcal": 355, "protein_g": 12.5, "carbs_g": 73.0, "sugars_g": 3.0, "fat_g": 1.5, "fiber_g": 3.0, "sodium_g": 0.005},
  {"id": "UG3yr", "energy_kcal": 135, "protein_g": 8.5, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 9.0, "fiber_g": 0.0, "sodium_g": 0.4},
  {"id": "D9pjU", "energy_kcal": 95, "protein_g": 9.0, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 5.0, "fiber_g": 0.0, "sodium_g": 0.4},
  {"id": "jqgMr", "energy_kcal": 82, "protein_g": 4.3, "carbs_g": 15.0, "sugars_g": 11.5, "fat_g": 0.5, "fiber_g": 2.5, "sodium_g": 0.05},
  {"id": "YBP3v", "energy_kcal": 160, "protein_g": 2.8, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 15.0, "fiber_g": 0.0, "sodium_g": 0.045},
  {"id": "0RRCu", "energy_kcal": 399, "protein_g": 0.0, "carbs_g": 99.8, "sugars_g": 99.8, "fat_g": 0.0, "fiber_g": 0.0, "sodium_g": 0.01},
  {"id": "7LB6c", "energy_kcal": 360, "protein_g": 12.0, "carbs_g": 72.0, "sugars_g": 2.5, "fat_g": 1.8, "fiber_g": 3.5, "sodium_g": 0.005},
  {"id": "aRYv0", "energy_kcal": 360, "protein_g": 12.0, "carbs_g": 72.0, "sugars_g": 2.5, "fat_g": 1.8, "fiber_g": 3.5, "sodium_g": 0.005},
  {"id": "upZy0", "energy_kcal": 355, "protein_g": 12.5, "carbs_g": 73.0, "sugars_g": 3.0, "fat_g": 1.5, "fiber_g": 3.0, "sodium_g": 0.005},
  {"id": "Ux1OE", "energy_kcal": 101, "protein_g": 1.0, "carbs_g": 25.8, "sugars_g": 22.1, "fat_g": 0.1, "fiber_g": 0.3, "sodium_g": 1.05},
  {"id": "xN6Lr", "energy_kcal": 320, "protein_g": 21.0, "carbs_g": 1.5, "sugars_g": 0.5, "fat_g": 25.0, "fiber_g": 0.0, "sodium_g": 1.1},
  {"id": "cTQ8k", "energy_kcal": 680, "protein_g": 1.0, "carbs_g": 0.6, "sugars_g": 0.6, "fat_g": 75.0, "fiber_g": 0.0, "sodium_g": 0.63},
  {"id": "vdPeM", "energy_kcal": 81, "protein_g": 5.4, "carbs_g": 14.4, "sugars_g": 5.6, "fat_g": 0.4, "fiber_g": 5.1, "sodium_g": 0.005},
  {"id": "q0jqY", "energy_kcal": 160, "protein_g": 2.8, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 15.0, "fiber_g": 0.0, "sodium_g": 0.045},
  {"id": "VBBo5", "energy_kcal": 255, "protein_g": 6.0, "carbs_g": 4.0, "sugars_g": 3.5, "fat_g": 24.0, "fiber_g": 0.2, "sodium_g": 0.45},
  {"id": "6viBk", "energy_kcal": 400, "protein_g": 0.0, "carbs_g": 100.0, "sugars_g": 100.0, "fat_g": 0.0, "fiber_g": 0.0, "sodium_g": 0.0},
  {"id": "Qo8AW", "energy_kcal": 185, "protein_g": 2.5, "carbs_g": 12.0, "sugars_g": 6.0, "fat_g": 14.0, "fiber_g": 3.5, "sodium_g": 2.8},
  {"id": "PIUhB", "energy_kcal": 82, "protein_g": 4.3, "carbs_g": 15.0, "sugars_g": 11.5, "fat_g": 0.5, "fiber_g": 2.5, "sodium_g": 0.05},
  {"id": "VgWzF", "energy_kcal": 245, "protein_g": 6.5, "carbs_g": 3.8, "sugars_g": 3.0, "fat_g": 23.0, "fiber_g": 0.5, "sodium_g": 0.55},
  {"id": "MBABh", "energy_kcal": 884, "protein_g": 0.0, "carbs_g": 0.0, "sugars_g": 0.0, "fat_g": 100.0, "fiber_g": 0.0, "sodium_g": 0.0},
  {"id": "R0Q2m", "energy_kcal": 168, "protein_g": 2.6, "carbs_g": 4.0, "sugars_g": 4.0, "fat_g": 15.0, "fiber_g": 0.0, "sodium_g": 0.04},
  {"id": "KClHf", "energy_kcal": 115, "protein_g": 11.0, "carbs_g": 1.5, "sugars_g": 1.5, "fat_g": 5.0, "fiber_g": 0.0, "sodium_g": 1.2},
  {"id": "HjAwA", "energy_kcal": 42, "protein_g": 3.4, "carbs_g": 5.0, "sugars_g": 5.0, "fat_g": 1.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "jx1YW", "energy_kcal": 63, "protein_g": 3.5, "carbs_g": 4.7, "sugars_g": 4.7, "fat_g": 3.5, "fiber_g": 0.0, "sodium_g": 0.04},
  {"id": "nST9o", "energy_kcal": 355, "protein_g": 12.5, "carbs_g": 73.0, "sugars_g": 3.0, "fat_g": 1.5, "fiber_g": 3.0, "sodium_g": 0.005},
  {"id": "EJ9gS", "energy_kcal": 717, "protein_g": 0.9, "carbs_g": 0.1, "sugars_g": 0.1, "fat_g": 81.0, "fiber_g": 0.0, "sodium_g": 0.011},
  {"id": "KD9fd", "energy_kcal": 19, "protein_g": 0.9, "carbs_g": 4.3, "sugars_g": 1.8, "fat_g": 0.1, "fiber_g": 2.9, "sodium_g": 0.66},
  {"id": "xuL8O", "energy_kcal": 12, "protein_g": 1.0, "carbs_g": 2.2, "sugars_g": 1.0, "fat_g": 0.1, "fiber_g": 1.1, "sodium_g": 1.1},
  {"id": "ERMbU", "energy_kcal": 12, "protein_g": 1.0, "carbs_g": 2.2, "sugars_g": 1.0, "fat_g": 0.1, "fiber_g": 1.1, "sodium_g": 1.1},
  {"id": "s9VwF", "energy_kcal": 14, "protein_g": 0.7, "carbs_g": 2.8, "sugars_g": 1.2, "fat_g": 0.1, "fiber_g": 0.8, "sodium_g": 0.85},
  {"id": "QicFV", "energy_kcal": 94, "protein_g": 8.5, "carbs_g": 11.5, "sugars_g": 11.0, "fat_g": 1.5, "fiber_g": 0.0, "sodium_g": 0.11},
  {"id": "xmrZo", "energy_kcal": 14, "protein_g": 0.7, "carbs_g": 2.8, "sugars_g": 1.2, "fat_g": 0.1, "fiber_g": 0.8, "sodium_g": 0.85},
  {"id": "nLk40", "energy_kcal": 164, "protein_g": 8.9, "carbs_g": 27.4, "sugars_g": 4.8, "fat_g": 2.6, "fiber_g": 7.6, "sodium_g": 0.24},
  {"id": "npLqb", "energy_kcal": 394, "protein_g": 5.8, "carbs_g": 3.7, "sugars_g": 3.7, "fat_g": 40.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "Sd1DZ", "energy_kcal": 300, "protein_g": 22.0, "carbs_g": 2.2, "sugars_g": 1.0, "fat_g": 22.4, "fiber_g": 0.0, "sodium_g": 0.45},
  {"id": "1M4ed", "energy_kcal": 210, "protein_g": 14.0, "carbs_g": 2.0, "sugars_g": 1.5, "fat_g": 16.0, "fiber_g": 0.0, "sodium_g": 1.15},
  {"id": "uJnKI", "energy_kcal": 275, "protein_g": 12.5, "carbs_g": 3.5, "sugars_g": 1.2, "fat_g": 23.5, "fiber_g": 0.0, "sodium_g": 0.95},
  {"id": "j9t1L", "energy_kcal": 122, "protein_g": 2.8, "carbs_g": 4.2, "sugars_g": 4.2, "fat_g": 10.0, "fiber_g": 0.0, "sodium_g": 0.04},
  {"id": "29jTR", "energy_kcal": 52, "protein_g": 2.5, "carbs_g": 7.5, "sugars_g": 3.8, "fat_g": 0.4, "fiber_g": 3.2, "sodium_g": 0.28},
  {"id": "Ref9I", "energy_kcal": 0, "protein_g": 0.0, "carbs_g": 0.0, "sugars_g": 0.0, "fat_g": 0.0, "fiber_g": 0.0, "sodium_g": 38.7},
  {"id": "D2Cv4", "energy_kcal": 60, "protein_g": 3.3, "carbs_g": 4.9, "sugars_g": 4.9, "fat_g": 3.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "5sUDu", "energy_kcal": 150, "protein_g": 7.1, "carbs_g": 5.2, "sugars_g": 1.2, "fat_g": 11.0, "fiber_g": 3.5, "sodium_g": 2.3},
  {"id": "98rzv", "energy_kcal": 139, "protein_g": 9.7, "carbs_g": 25.0, "sugars_g": 0.3, "fat_g": 0.4, "fiber_g": 6.3, "sodium_g": 0.005},
  {"id": "Jqacx", "energy_kcal": 60, "protein_g": 3.2, "carbs_g": 4.8, "sugars_g": 4.8, "fat_g": 3.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "Yf9Cc", "energy_kcal": 345, "protein_g": 2.1, "carbs_g": 3.1, "sugars_g": 3.1, "fat_g": 38.0, "fiber_g": 0.0, "sodium_g": 0.03},
  {"id": "VQ9Kg", "energy_kcal": 149, "protein_g": 6.4, "carbs_g": 33.1, "sugars_g": 1.0, "fat_g": 0.5, "fiber_g": 2.1, "sodium_g": 0.017},
  {"id": "rfwpZ", "energy_kcal": 450, "protein_g": 4.5, "carbs_g": 6.5, "sugars_g": 1.2, "fat_g": 46.0, "fiber_g": 2.2, "sodium_g": 1.1},
  {"id": "4v1OJ", "energy_kcal": 320, "protein_g": 8.0, "carbs_g": 52.0, "sugars_g": 15.0, "fat_g": 6.5, "fiber_g": 5.5, "sodium_g": 9.5},
  {"id": "dIQNq", "energy_kcal": 72, "protein_g": 3.8, "carbs_g": 4.2, "sugars_g": 4.2, "fat_g": 4.5, "fiber_g": 0.0, "sodium_g": 0.055},
  {"id": "YUANV", "energy_kcal": 295, "protein_g": 12.0, "carbs_g": 45.0, "sugars_g": 10.0, "fat_g": 5.0, "fiber_g": 4.0, "sodium_g": 11.2},
  {"id": "ebIPD", "energy_kcal": 81, "protein_g": 5.4, "carbs_g": 14.4, "sugars_g": 5.6, "fat_g": 0.4, "fiber_g": 5.1, "sodium_g": 0.005},
  {"id": "On4c4", "energy_kcal": 280, "protein_g": 14.0, "carbs_g": 2.0, "sugars_g": 1.5, "fat_g": 24.0, "fiber_g": 0.0, "sodium_g": 1.35},
  {"id": "HoC2c", "energy_kcal": 210, "protein_g": 14.0, "carbs_g": 2.0, "sugars_g": 1.5, "fat_g": 16.0, "fiber_g": 0.0, "sodium_g": 1.15},
  {"id": "qD5bs", "energy_kcal": 392, "protein_g": 35.8, "carbs_g": 3.2, "sugars_g": 0.1, "fat_g": 25.8, "fiber_g": 0.0, "sodium_g": 1.6},
  {"id": "myhDR", "energy_kcal": 310, "protein_g": 2.2, "carbs_g": 3.2, "sugars_g": 3.2, "fat_g": 32.0, "fiber_g": 0.0, "sodium_g": 0.035},
  {"id": "QxXJS", "energy_kcal": 135, "protein_g": 8.5, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 9.0, "fiber_g": 0.0, "sodium_g": 0.4},
  {"id": "BiYgU", "energy_kcal": 1, "protein_g": 0.1, "carbs_g": 0.3, "sugars_g": 0.0, "fat_g": 0.0, "fiber_g": 0.0, "sodium_g": 0.002},
  {"id": "qPcRP", "energy_kcal": 95, "protein_g": 9.0, "carbs_g": 3.5, "sugars_g": 3.5, "fat_g": 5.0, "fiber_g": 0.0, "sodium_g": 0.4},
  {"id": "tArZj", "energy_kcal": 343, "protein_g": 13.3, "carbs_g": 71.5, "sugars_g": 0.0, "fat_g": 3.4, "fiber_g": 10.0, "sodium_g": 0.001},
  {"id": "oDbOu", "energy_kcal": 353, "protein_g": 24.6, "carbs_g": 63.4, "sugars_g": 2.0, "fat_g": 1.1, "fiber_g": 10.7, "sodium_g": 0.006},
  {"id": "oKo11", "energy_kcal": 353, "protein_g": 24.6, "carbs_g": 63.4, "sugars_g": 2.0, "fat_g": 1.1, "fiber_g": 10.7, "sodium_g": 0.006},
  {"id": "DAlO4", "energy_kcal": 285, "protein_g": 12.0, "carbs_g": 2.5, "sugars_g": 2.5, "fat_g": 25.0, "fiber_g": 0.0, "sodium_g": 0.4},
  {"id": "Ph4Hk", "energy_kcal": 333, "protein_g": 23.4, "carbs_g": 60.3, "sugars_g": 2.1, "fat_g": 0.8, "fiber_g": 15.2, "sodium_g": 0.024},
  {"id": "6FDbO", "energy_kcal": 65, "protein_g": 3.3, "carbs_g": 4.9, "sugars_g": 4.9, "fat_g": 3.6, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "0iVBl", "energy_kcal": 255, "protein_g": 6.0, "carbs_g": 4.0, "sugars_g": 3.5, "fat_g": 25.0, "fiber_g": 0.2, "sodium_g": 0.45},
  {"id": "K27QG", "energy_kcal": 610, "protein_g": 18.0, "carbs_g": 12.0, "sugars_g": 0.5, "fat_g": 56.0, "fiber_g": 5.0, "sodium_g": 0.015},
  {"id": "gi1Ni", "energy_kcal": 304, "protein_g": 0.3, "carbs_g": 82.4, "sugars_g": 82.1, "fat_g": 0.0, "fiber_g": 0.0, "sodium_g": 0.004},
  {"id": "mxgG8", "energy_kcal": 185, "protein_g": 2.5, "carbs_g": 12.0, "sugars_g": 6.0, "fat_g": 14.0, "fiber_g": 3.5, "sodium_g": 2.8},
  {"id": "tlF4G", "energy_kcal": 640, "protein_g": 1.0, "carbs_g": 3.0, "sugars_g": 2.5, "fat_g": 70.0, "fiber_g": 0.0, "sodium_g": 0.6},
  {"id": "K4pKb", "energy_kcal": 250, "protein_g": 6.0, "carbs_g": 4.0, "sugars_g": 3.5, "fat_g": 24.0, "fiber_g": 0.0, "sodium_g": 0.35},
  {"id": "dyl6G", "energy_kcal": 310, "protein_g": 2.2, "carbs_g": 3.2, "sugars_g": 3.2, "fat_g": 32.0, "fiber_g": 0.0, "sodium_g": 0.035},
  {"id": "RTQgq", "energy_kcal": 105, "protein_g": 5.0, "carbs_g": 4.5, "sugars_g": 4.5, "fat_g": 6.5, "fiber_g": 0.0, "sodium_g": 0.065},
  {"id": "OKTNt", "energy_kcal": 280, "protein_g": 13.0, "carbs_g": 18.0, "sugars_g": 1.5, "fat_g": 17.5, "fiber_g": 1.2, "sodium_g": 0.65},
  {"id": "qmm4r", "energy_kcal": 63, "protein_g": 3.5, "carbs_g": 4.7, "sugars_g": 4.7, "fat_g": 3.5, "fiber_g": 0.0, "sodium_g": 0.04},
  {"id": "GOWHu", "energy_kcal": 360, "protein_g": 7.5, "carbs_g": 78.0, "sugars_g": 0.5, "fat_g": 1.0, "fiber_g": 2.0, "sodium_g": 0.45},
  {"id": "kslEw", "energy_kcal": 365, "protein_g": 2.0, "carbs_g": 3.0, "sugars_g": 3.0, "fat_g": 38.0, "fiber_g": 0.0, "sodium_g": 0.03},
  {"id": "2PApK", "energy_kcal": 150, "protein_g": 7.1, "carbs_g": 5.2, "sugars_g": 1.2, "fat_g": 11.0, "fiber_g": 3.5, "sodium_g": 2.3},
  {"id": "7uoAj", "energy_kcal": 72, "protein_g": 3.8, "carbs_g": 4.2, "sugars_g": 4.2, "fat_g": 4.5, "fiber_g": 0.0, "sodium_g": 0.055},
  {"id": "ocG2Q", "energy_kcal": 80, "protein_g": 11.0, "carbs_g": 5.5, "sugars_g": 5.0, "fat_g": 1.5, "fiber_g": 0.0, "sodium_g": 0.11},
  {"id": "sUkQh", "energy_kcal": 715, "protein_g": 0.0, "carbs_g": 0.0, "sugars_g": 0.0, "fat_g": 80.0, "fiber_g": 0.0, "sodium_g": 0.65},
  {"id": "pfOM1", "energy_kcal": 60, "protein_g": 3.3, "carbs_g": 4.9, "sugars_g": 4.9, "fat_g": 3.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "j3b2r", "energy_kcal": 300, "protein_g": 22.0, "carbs_g": 2.2, "sugars_g": 1.0, "fat_g": 22.4, "fiber_g": 0.0, "sodium_g": 0.45},
  {"id": "pTuiH", "energy_kcal": 101, "protein_g": 1.0, "carbs_g": 25.8, "sugars_g": 22.1, "fat_g": 0.1, "fiber_g": 0.3, "sodium_g": 0.9},
  {"id": "A2tIB", "energy_kcal": 350, "protein_g": 4.5, "carbs_g": 12.0, "sugars_g": 10.0, "fat_g": 32.0, "fiber_g": 0.0, "sodium_g": 0.05},
  {"id": "BWeQe", "energy_kcal": 105, "protein_g": 16.0, "carbs_g": 3.5, "sugars_g": 2.5, "fat_g": 3.0, "fiber_g": 0.0, "sodium_g": 1.15},
  {"id": "RHl3V", "energy_kcal": 210, "protein_g": 14.0, "carbs_g": 2.0, "sugars_g": 1.5, "fat_g": 16.0, "fiber_g": 0.0, "sodium_g": 1.15},
  {"id": "HkKcT", "energy_kcal": 310, "protein_g": 8.5, "carbs_g": 12.0, "sugars_g": 1.2, "fat_g": 25.5, "fiber_g": 5.5, "sodium_g": 0.48},
  {"id": "4QILv", "energy_kcal": 245, "protein_g": 7.5, "carbs_g": 14.5, "sugars_g": 1.0, "fat_g": 18.0, "fiber_g": 5.2, "sodium_g": 0.52},
  {"id": "HSTAh", "energy_kcal": 14, "protein_g": 0.7, "carbs_g": 2.8, "sugars_g": 1.2, "fat_g": 0.1, "fiber_g": 0.8, "sodium_g": 0.85},
  {"id": "GKi0h", "energy_kcal": 12, "protein_g": 1.0, "carbs_g": 2.2, "sugars_g": 1.0, "fat_g": 0.1, "fiber_g": 1.1, "sodium_g": 1.1},
  {"id": "LfmUE", "energy_kcal": 130, "protein_g": 7.5, "carbs_g": 4.0, "sugars_g": 4.0, "fat_g": 10.0, "fiber_g": 0.0, "sodium_g": 0.07},
  {"id": "frsaZ", "energy_kcal": 280, "protein_g": 13.0, "carbs_g": 18.0, "sugars_g": 1.5, "fat_g": 17.5, "fiber_g": 1.2, "sodium_g": 0.65},
  {"id": "4XCWf", "energy_kcal": 105, "protein_g": 8.4, "carbs_g": 18.1, "sugars_g": 0.0, "fat_g": 0.0, "fiber_g": 0.0, "sodium_g": 0.03},
  {"id": "YPri0", "energy_kcal": 210, "protein_g": 28.0, "carbs_g": 0.1, "sugars_g": 0.1, "fat_g": 9.0, "fiber_g": 0.0, "sodium_g": 0.65},
  {"id": "NX3dn", "energy_kcal": 265, "protein_g": 0.8, "carbs_g": 11.5, "sugars_g": 8.5, "fat_g": 24.0, "fiber_g": 0.2, "sodium_g": 1.1},
]


def _to_nutrition(entry: dict) -> dict:
    return {k: entry[k] for k in entry if k != "id"}


def patch(write: bool) -> None:
    from config import COLLECTION, MONGO_ATLAS_URI, MONGO_LOCAL_URI

    targets = []
    if MONGO_ATLAS_URI:
        targets.append(("Atlas", MONGO_ATLAS_URI))
    if MONGO_LOCAL_URI:
        targets.append(("Local", MONGO_LOCAL_URI))

    if not targets:
        logger.error("No MongoDB URIs configured.")
        sys.exit(1)

    logger.info(f"[patch] {len(NUTRITION_BY_ID)} entries to apply")

    for label, uri in targets:
        updated = 0
        not_found = 0
        try:
            client = pymongo.MongoClient(uri, serverSelectionTimeoutMS=5000)
            db = client.get_default_database()
            col = db[COLLECTION]

            for entry in NUTRITION_BY_ID:
                doc_id = entry["id"]
                nutrition = _to_nutrition(entry)
                existing = col.find_one({"_id": doc_id}, {"nutrition_per_100g": 1})
                if existing is None:
                    not_found += 1
                    logger.debug(f"[{label}] _id {doc_id} not found")
                    continue
                if write:
                    col.update_one({"_id": doc_id}, {"$set": {"nutrition_per_100g": nutrition}})
                updated += 1

            client.close()
            action = "Updated" if write else "Would update"
            logger.info(f"[db] [{label}] {action}: {updated}, not found: {not_found}")
        except Exception as exc:
            logger.error(f"[db] [{label}] Connection failed: {exc}")

    if not write:
        logger.info("[patch] DRY RUN — pass --write to apply.")
    else:
        logger.info("[patch] Done.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Apply Gemini nutrition to Atlas products by _id")
    parser.add_argument("--write", action="store_true", help="Apply updates (default is dry run)")
    args = parser.parse_args()
    patch(write=args.write)
