/**
 * Kit ownership list — which FoodVibe workflow files the ai-workflow-kit owns since the phase 5 cutover
 * (ADR 0015, plan 360). Kit-owned = manifest tiers core, layer:cursor and pack:*. Templates (seeds) and
 * project files stay FoodVibe-owned.
 *
 * Usage:
 *   node scripts/kit-owned.mjs --write          # regenerate docs/workflow-kit/kit-owned.json from the manifest
 *   node scripts/kit-owned.mjs --check          # fail when the list is out of sync with the manifest
 *   node scripts/kit-owned.mjs --file=<path>    # exit 1 + "KIT_OWNED: yes" when the path is kit-owned (used by scope-guard.sh)
 *
 * Node built-ins only. --file exits 0 ("no") when the list file is absent, so the guard fails open.
 */
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve, join, dirname, relative } from 'path'
import { fileURLToPath } from 'url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const manifestPath = join(root, 'docs/workflow-kit/manifest.json')
const listPath = join(root, 'docs/workflow-kit/kit-owned.json')
const argv = process.argv.slice(2)

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8').replace(/^﻿/, ''))
const isOwnedTier = (t) => t === 'core' || t === 'layer:cursor' || t.startsWith('pack:')
const fromManifest = () => readJson(manifestPath).entries.filter((e) => isOwnedTier(e.tier)).map((e) => e.path).sort()

const fileArg = argv.find((a) => a.startsWith('--file='))
if (fileArg) {
  if (!existsSync(listPath)) {
    console.log('KIT_OWNED: no — no kit-owned list')
    process.exit(0)
  }
  const rel = relative(root, resolve(fileArg.slice('--file='.length))).replace(/\\/g, '/')
  if (rel.startsWith('..') || !new Set(readJson(listPath).files).has(rel)) {
    console.log(`KIT_OWNED: no — ${rel}`)
    process.exit(0)
  }
  console.log(`KIT_OWNED: yes - ${rel} is owned by the workflow kit. Change it in ../ai-workflow-kit, then apply the kit diff here as a patch (docs/brain/decisions/0018-kit-changes-reach-foodvibe-as-patches.md); or list it in the plan's Read-Write Scope and work in a slot.`)
  process.exit(1)
}

const expected = fromManifest()
if (argv.includes('--write')) {
  const doc = { $comment: 'Generated by scripts/kit-owned.mjs --write from manifest.json (tiers core, layer:cursor, pack:*). Do not edit.', files: expected }
  writeFileSync(listPath, JSON.stringify(doc, null, 2) + '\n', 'utf8')
  console.log(`KIT_OWNED: wrote — ${expected.length} kit-owned files`)
  process.exit(0)
}

if (!existsSync(listPath)) {
  console.error('KIT_OWNED: FAIL — docs/workflow-kit/kit-owned.json is missing; run: node scripts/kit-owned.mjs --write')
  process.exit(1)
}
const actual = readJson(listPath).files
const missing = expected.filter((p) => !actual.includes(p))
const extra = actual.filter((p) => !expected.includes(p))
if (missing.length > 0 || extra.length > 0) {
  console.error(`KIT_OWNED: FAIL — list out of sync with manifest (${missing.length} missing, ${extra.length} extra); run: node scripts/kit-owned.mjs --write`)
  process.exit(1)
}
console.log(`KIT_OWNED: ok — ${expected.length} kit-owned files, list in sync with manifest`)
