/**
 * Scope check — enforces a plan's Read-Write Scope for Workers. Shared by
 * scope-guard.sh (PreToolUse), ship-prep.mjs and take-plan.mjs.
 * See plans/326-planner-worker-workflow.plan.md.
 *
 * Usage:
 *   node scripts/scope-check.mjs --file=<path> [--plan=<path>]
 *   node scripts/scope-check.mjs --diff=<base> [--plan=<path>]
 *   node scripts/scope-check.mjs --overlap --plan=<path>
 *   node scripts/scope-check.mjs --drift [--plan=<path>]
 *   node scripts/scope-check.mjs --arch --plan=<path>                   (BLOCK)
 *   node scripts/scope-check.mjs --arch --diff=<base> [--plan=<path>]   (WARN, exit 0)
 *
 * --plan defaults to the active slot's .worktree-plan. Exit 1 on a missing
 * plan / scope block, on --file/--diff finding an out-of-scope file, on
 * --overlap finding a shared glob with another active plan, or on --drift
 * finding an in-scope commit since the plan's Snapshot (or, without one, since
 * the commit that added the plan).
 *
 * --arch reads the architecture invariants registry (docs/brain/invariants.md; see
 * scripts/lib/invariants.mjs). With --plan: exit 1 when the plan's scope touches an
 * invariant that has no "## Architecture Impact" entry, or a deviation/changes entry
 * lacks "Arch-approved: Human" or a valid ADR; a plan numbered below "Enforced from plan:"
 * without the section prints "ARCH: skipped (grandfathered)". With --diff: print
 * "ARCH: warn …" lines for touched invariants the active plan doesn't cover and for
 * "Human decision" notes that name no INV-n / ADR; always exit 0. No registry file:
 * "ARCH: skipped (no registry)", exit 0. --registry=<path> overrides the file (tests).
 */
import { readFileSync, existsSync, readdirSync } from 'fs'
import { execFileSync } from 'child_process'
import { resolve, dirname, join, relative, isAbsolute } from 'path'
import { fileURLToPath } from 'url'
import picomatch from 'picomatch'
import { activePlanPath } from './lib/slot.mjs'
import { extractScopeGlobs } from './lib/plan-scope.mjs'
import { parseInvariants, checkPlanArch, diffArchWarnings, decisionWithoutAdr, parseAddedLines } from './lib/invariants.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')

// Append-only hotspots (Planner-Worker rules): every plan may touch
// these regardless of its own Read-Write Scope, but must never remove or
// rewrite an existing entry — only add to them.
const HOTSPOTS = [
  'public/assets/data/dictionary.json',
  'src/styles.scss', 'src/app/app.routes.ts'
]

// Regenerated by kit scripts (kit-owned.mjs --write, the manifest tools): never a decision for the Human.
const GENERATED = [
  'docs/workflow-kit/kit-owned.json',
  'docs/workflow-kit/manifest.json',
  'docs/workflow-kit/manifest.md'
]

// Shared files most plans append to: a commit there is not drift for this plan.
const DRIFT_NOISE = [...HOTSPOTS, ...GENERATED, 'AGENTS.md', 'CHANGELOG.md', 'docs/brain/index.md']

function fail(message) {
  console.error(`SCOPE_CHECK: ${message}`)
  process.exit(1)
}

function parseArgs(argv) {
  const out = {}
  for (const arg of argv) {
    if (!arg.startsWith('--')) continue
    const eq = arg.indexOf('=')
    if (eq >= 0) out[arg.slice(2, eq)] = arg.slice(eq + 1)
    else out[arg.slice(2)] = true
  }
  return out
}

function git(cmdArgs) {
  try {
    return execFileSync('git', cmdArgs, { cwd: repoRoot, encoding: 'utf8' }).replace(/\r?\n+$/, '')
  } catch {
    return ''
  }
}

function normalize(p) {
  return String(p).replace(/\\/g, '/')
}

function sanitizeBranch(branch) {
  return branch.replace(/[^a-zA-Z0-9]/g, '-')
}

function readPlanFile(planPath) {
  const abs = join(repoRoot, planPath)
  if (!existsSync(abs)) fail(`plan not found: ${planPath}`)
  return readFileSync(abs, 'utf8')
}

function extractField(planText, name) {
  const m = planText.match(new RegExp(`^${name}:\\s*(\\S+)`, 'm'))
  return m ? m[1] : null
}

function resolvePlanPath(args) {
  if (args.plan) return normalize(args.plan)
  const active = activePlanPath()
  if (!active) fail('no --plan given and no active plan for this slot (.worktree-plan missing)')
  return normalize(active)
}

function buildMatcher(planPath) {
  const planText = readPlanFile(planPath)
  const scopeGlobs = extractScopeGlobs(planText)
  if (!scopeGlobs) fail(`${planPath} has no readable scope under "## Read-Write Scope" (need a \`\`\`scope block or a **Scope:** list of \`globs\`)`)

  const branch = sanitizeBranch(git(['branch', '--show-current']))
  const alwaysAllowed = [
    planPath,
    `docs/session-state-${branch}.md`,
    '.claude/sessions/**',
    '.worktree-*',
    'docs/brain/**', // the merge gate's brain capture appends here
    ...HOTSPOTS,
    ...GENERATED
  ]

  const allowed = [...alwaysAllowed, ...scopeGlobs]
  const isMatch = picomatch(allowed, { dot: true })
  return { isMatch, planText, scopeGlobs }
}

function changedFiles(base) {
  const ranged = git(['diff', '--name-only', `${base}...HEAD`])
  const staged = git(['diff', '--name-only', '--cached'])
  const unstaged = git(['diff', '--name-only'])
  const untracked = git(['ls-files', '--others', '--exclude-standard'])

  const all = new Set()
  for (const block of [ranged, staged, unstaged, untracked]) {
    for (const line of block.split('\n')) {
      const t = line.trim()
      if (t) all.add(normalize(t))
    }
  }
  return [...all]
}

function cmdFile(args) {
  const planPath = resolvePlanPath(args)
  const { isMatch } = buildMatcher(planPath)
  // Hooks pass absolute paths (C:\...\file); scope globs are repo-relative.
  const raw = normalize(args.file)
  const file = isAbsolute(raw) ? normalize(relative(repoRoot, raw)) : raw

  if (isMatch(file)) {
    console.log(`SCOPE: ok ${file}`)
    process.exit(0)
  }
  console.error(`SCOPE: out ${file}`)
  process.exit(1)
}

function cmdDiff(args) {
  const planPath = resolvePlanPath(args)
  const { isMatch } = buildMatcher(planPath)
  const out = changedFiles(args.diff).filter(f => !isMatch(f))

  if (!out.length) {
    console.log('SCOPE: ok')
    return
  }
  console.log('SCOPE: out')
  for (const f of out) console.log(`  ${f}`)
  process.exit(1)
}

function cmdOverlap(args) {
  if (!args.plan) fail('--overlap requires --plan=<path>')
  const planPath = normalize(args.plan)
  const { scopeGlobs } = buildMatcher(planPath)

  const plansDir = join(repoRoot, 'plans')
  const siblingFiles = existsSync(plansDir)
    ? readdirSync(plansDir).filter(f => f.endsWith('.plan.md')).map(f => `plans/${f}`)
    : []

  const overlaps = []
  for (const other of siblingFiles) {
    if (other === planPath) continue
    const otherText = readFileSync(join(repoRoot, other), 'utf8')
    if (extractField(otherText, 'Status') !== 'active') continue
    const otherGlobs = extractScopeGlobs(otherText)
    if (!otherGlobs) continue
    const shared = scopeGlobs.filter(g => otherGlobs.includes(g))
    if (shared.length) overlaps.push({ plan: other, globs: shared })
  }

  if (!overlaps.length) {
    console.log('OVERLAP: none')
    return
  }
  console.log('OVERLAP:')
  for (const o of overlaps) console.log(`  ${o.plan}: ${o.globs.join(', ')}`)
  process.exit(1)
}

function cmdDrift(args) {
  const planPath = resolvePlanPath(args)
  const planText = readPlanFile(planPath)
  let snapshot = extractField(planText, 'Snapshot')
  if (!snapshot) {
    // No Snapshot line: the commit that added the plan on main is the next best baseline.
    snapshot = git(['log', '--diff-filter=A', '-1', '--format=%H', 'origin/main', '--', planPath])
    if (!snapshot) fail(`${planPath} has no "Snapshot:" line and is not on origin/main`)
    console.log(`SCOPE_CHECK: no "Snapshot:" line - checking drift since the commit that added the plan (${snapshot.slice(0, 8)})`)
  }

  const scopeGlobs = extractScopeGlobs(planText)
  if (!scopeGlobs) fail(`${planPath} has no readable scope under "## Read-Write Scope" (need a \`\`\`scope block or a **Scope:** list of \`globs\`)`)

  // Hotspots, generated files and shared append-only docs are touched by every plan — a commit
  // there from someone else's work isn't drift for this plan.
  const pathspecs = scopeGlobs.filter(g => !DRIFT_NOISE.includes(g)).map(g => `:(glob)${g}`)
  const out = pathspecs.length ? git(['log', '--oneline', `${snapshot}..origin/main`, '--', ...pathspecs]) : ''

  if (!out) {
    console.log('REALITY: clean')
    return
  }
  console.log('REALITY: drift')
  console.log(out)
  process.exit(1)
}

function readRegistry(args) {
  const path = normalize(args.registry || 'docs/brain/invariants.md')
  const abs = isAbsolute(path) ? path : join(repoRoot, path)
  if (!existsSync(abs)) {
    if (args.registry) fail(`invariants registry not found: ${path}`)
    console.log('ARCH: skipped (no registry)')
    process.exit(0)
  }
  return parseInvariants(readFileSync(abs, 'utf8'))
}

function cmdArchPlan(args) {
  const planPath = normalize(args.plan)
  const planText = readPlanFile(planPath)
  const registry = readRegistry(args)
  const scopeGlobs = extractScopeGlobs(planText)
  if (!scopeGlobs) fail(`${planPath} has no readable scope under "## Read-Write Scope" (need a \`\`\`scope block or a **Scope:** list of \`globs\`)`)
  const { ok, lines } = checkPlanArch({
    planPath,
    planText,
    scopeGlobs,
    registry,
    trackedFiles: git(['ls-files']).split('\n').filter(Boolean),
    adrExists: (p) => existsSync(join(repoRoot, p))
  })
  for (const l of lines) (ok ? console.log : console.error)(l)
  process.exit(ok ? 0 : 1)
}

// Added lines (with line numbers) in session-state and plan files since the merge base with <base>.
function addedDecisionLines(base) {
  const mergeBase = git(['merge-base', base, 'HEAD']) || base
  const specs = [':(glob)docs/session-state*.md', ':(glob)plans/*.plan.md']
  const added = parseAddedLines(git(['diff', '-U0', '--no-color', mergeBase, '--', ...specs]))
  const untracked = git(['ls-files', '--others', '--exclude-standard', '--', ...specs]).split('\n').filter(Boolean)
  for (const f of untracked) {
    readFileSync(join(repoRoot, f), 'utf8').split(/\r?\n/).forEach((text, i) => added.push({ file: normalize(f), line: i + 1, text }))
  }
  return added
}

function cmdArchDiff(args) {
  const registry = readRegistry(args)
  const planPath = args.plan ? normalize(args.plan) : activePlanPath()
  const planAbs = planPath ? join(repoRoot, planPath) : null
  const planText = planAbs && existsSync(planAbs) ? readFileSync(planAbs, 'utf8') : null
  const lines = [
    ...diffArchWarnings({ changedFiles: changedFiles(args.diff), registry, planText }),
    ...decisionWithoutAdr(addedDecisionLines(args.diff))
  ]
  console.log(lines.length ? lines.join('\n') : 'ARCH: ok (diff)')
}

const args = parseArgs(process.argv.slice(2))

if (args.arch && args.diff) cmdArchDiff(args)
else if (args.arch && args.plan) cmdArchPlan(args)
else if (args.arch) fail('--arch needs --plan=<p> or --diff=<base>')
else if (args.file) cmdFile(args)
else if (args.diff) cmdDiff(args)
else if (args.overlap) cmdOverlap(args)
else if (args.drift) cmdDrift(args)
else fail('usage: --file=<p> | --diff=<base> | --overlap --plan=<p> | --drift [--plan=<p>] | --arch --plan=<p> | --arch --diff=<base>')
